### ISSUE TITLE
JDK9 support

### ISSUE THREAD

**Issue by tirkarthi** [alexander-yakushev/compliment#52]
I tried adding JDK9 to travis CI for testing and there were some failures as below :  

https://travis-ci.org/tirkarthi/compliment/jobs/347215695

**Comment by tirkarthi** [comment]
One basic change I was able to see between JDK8 and JDK9 for `defrecord` as below : 

JDK8 

```clojure
user=> (defrecord Animal [])
user.Animal
user=> (require '[compliment.sources.ns-mappings :as src])
nil
user=> (src/candidates "Ani" *ns* nil)
({:candidate "Animal", :type :class, :package nil})
```

JDK9

```clojure
user=> (defrecord Animal [])
user.Animal
user=> (require '[compliment.sources.ns-mappings :as src])
nil
user=> (src/candidates "Ani" *ns* nil)
({:candidate "Animal", :type :class, :package "user"})
```

**Comment by alexander-yakushev** [comment]
Thanks! I fixed the test and added JDK9 as a testing target.

**Comment by tirkarthi** [comment]
I think there needs to be different assertions to be done for different versions of JDK. I don't know if there is a cleaner way to do this in Clojure or in the current testing framework to keep the compatibility with all versions of JDK.

**Comment by alexander-yakushev** [comment]
It looks like more than that. Many classnames are not being completed - maybe JDK9 changed the way that native Java classes should be discovered from classpath.

**Comment by tirkarthi** [comment]
Some of the classes were removed. I fixed a related one in https://github.com/ninjudd/clojure-complete/pull/25 where `java.ext.dirs` and `sun.boot.class.path` were removed causing NPE. It's handled in compliment at https://github.com/alexander-yakushev/compliment/blob/0f6d907b6b2c7f0d45d0763f84e676676bb8bed6/src/compliment/utils.clj#L98-L99 
There were some classpath related changes that caused breakage in Clojure ecosystem with respect to JDK9.

**Comment by alexander-yakushev** [comment]
I found the issue. Base Java classes don't live in `rt.jar` anymore which was accessible through classpath scanning. Instead, now I have to read all the base modules.

Funnily enough, this still doesn't work on JDK9 but I managed to get it working on JDK10. I call this good enough since there's no reason to stay at JDK9 anyway.
